[workspace]
default-members = [
    "librobo"
]
members = [
    "librobo",
    "librobo-macro",
    "librobo-nostd",
    "librobo-nostd-macro"
]
resolver = "2"

[profile.release]
codegen-units = 1
debug = true
lto = true
