[dependencies]
heapless = { workspace = true }
num-traits = { workspace = true }

[package]
authors = [
    "Sora Tonami <ms0503@outlook.com>"
]
edition = "2021"
name = "librobo-nostd"
readme = "../README.md"
version = "0.1.0"
