[dependencies]
librobo-macro = { path = "../librobo-macro" }
log = { default-features = false, version = "0.4" }
num = "0.4"

[features]
bind-c = []
controller = [
    "librobo-macro/controller"
]
default = [
    "controller",
    "encoder",
    "servo",
    "steering"
]
encoder = []
servo = []
steering = []
steering-crawler = [
    "steering"
]
steering-quad-mechanum = [
    "steering"
]
steering-quad-omni = [
    "steering"
]

[lib]
crate-type = [
    "cdylib",
    "rlib",
    "staticlib"
]
name = "robo"

[package]
authors = [
    "Sora Tonami <ms0503@outlook.com>"
]
edition = "2021"
name = "librobo"
readme = "../README.md"
version = "0.1.0"
