[dependencies]
log = { default-features = false, version = "0.4" }
num = "0.4"

[features]
bind-c = []
default = [
    "controller",
    "encoder"
]
encoder = []

[lib]
crate-type = [
    "cdylib",
    "rlib",
    "staticlib"
]
name = "robo"

[package]
authors = [
    "Sora Tonami <ms0503@outlook.com>"
]
edition = "2021"
name = "librobo"
readme = "../README.md"
version = "0.1.0"
