[dependencies]
num = "0.4"

[features]
bind-c = []
default = [
    "bind-c"
]

[lib]
crate-type = [
    "cdylib",
    "rlib",
    "staticlib"
]

[package]
authors = [
    "Sora Tonami <ms0503@outlook.com>"
]
edition = "2021"
name = "librobo"
readme = "../README.md"
version = "0.1.0"
