env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docs
        run: cargo doc --no-deps --all --verbose --features all-std
      - name: Copy static docs
        run: cp -rv docs/* target/doc
      - name: Deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc
  deploy-doc:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: doc
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
name: Rust
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
